# -*- coding: utf-8 -*-
"""challenge_week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jzu2GG-aoehulzzQUxRn2dh615DAIZ1y

## Visualización de los datos (Punto a)

En este apartado se realiza la carga y visualización de la base de datos *BreastCancer.csv*, la cual contiene información de 569 observaciones con dos características por muestra, junto con su respectiva etiqueta de clasificación (0 o 1).

El objetivo es explorar la distribución de los datos en el espacio de características y analizar visualmente si existe separación entre las clases.
"""

import pandas as pd

# Cargar el archivo
data = pd.read_csv("BreastCancer.csv")

# Mostrar las primeras filas
data.head()

data['grupo_dup'] = data.groupby(['radius_mean', 'smoothness_mean']).ngroup()

duplicados = data[data.duplicated(subset=['radius_mean', 'smoothness_mean'], keep=False)]

duplicados.sort_values('grupo_dup')

duplicados.groupby(['radius_mean', 'smoothness_mean']).indices

"""### Carga y organización de los datos

Se separan las variables del conjunto de datos en:

- $X \in \mathbb{R}^{m \times 2}$: matriz de características, donde cada fila corresponde a un vector $(x_1, x_2)$.
- $t \in \{0,1\}^m$: vector de etiquetas, donde cada valor indica la clase real de cada observación.

Se asume que la última columna del conjunto de datos corresponde a la variable objetivo.
"""

# Separar características y etiquetas
X = data.iloc[:, :-1].values   # x1, x2
t = data.iloc[:, -1].values    # etiquetas

# Ver dimensiones
print("Shape de X:", X.shape)
print("Shape de t:", t.shape)

"""### Gráfico de dispersión

Se construye un gráfico de dispersión para representar cada observación en el plano $(x_1, x_2)$.

Para facilitar la interpretación:

- Las observaciones con $t = 0$ se representan en color azul.
- Las observaciones con $t = 1$ se representan en color rojo.

Esto permite visualizar la distribución de los datos en el espacio de características.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

# Clase 0
plt.scatter(X[t == 0, 0], X[t == 0, 1],
            color='blue', label='Clase 0', alpha=0.6)
# Selecciona SOLO los puntos cuya etiqueta es 0
# X[t == 0, 0] → valores de x1 de clase 0
# X[t == 0, 1] → valores de x2 de clase 0
# Se grafican en azul

# Clase 1
plt.scatter(X[t == 1, 0], X[t == 1, 1],
            color='red', label='Clase 1', alpha=0.6)
# Selecciona SOLO los puntos cuya etiqueta es 1
# Se grafican en rojo

plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.title("Distribución de los datos - BreastCancer")

plt.legend()   # Muestra la leyenda (Clase 0, Clase 1)
plt.grid()

plt.show()

"""### Análisis visual

A partir del gráfico de dispersión, se observa que las clases presentan una tendencia de separación en el espacio de características, principalmente a lo largo del eje $x_1$. Sin embargo, existe una región de solapamiento entre ambas clases, lo que indica que los datos no son perfectamente separables de forma lineal.

A pesar de esto, una frontera de decisión lineal puede aproximar adecuadamente la separación entre clases, lo cual justifica el uso de un modelo de regresión logística.

## Frontera de decisión (Punto b)

En este apartado se implementa una función que permite graficar la frontera de decisión asociada a un vector de parámetros:

$$
w = [w_1, w_2, w_3]^T
$$

La frontera de decisión está definida por la ecuación:

$$
w_1 x_1 + w_2 x_2 + w_3 = 0
$$

Despejando $x_2$, se obtiene:

$$
x_2 = \frac{-w_1 x_1 - w_3}{w_2}
$$

Esta forma permite representar la recta en el plano $(x_1, x_2)$ y visualizar cómo el modelo separa las clases observadas en el punto (a).
"""

def plot_recta(w, X, t):
    import numpy as np
    import matplotlib.pyplot as plt

    # Crear figura
    plt.figure(figsize=(8,6))

    # Graficar datos (igual que punto a)
    # Clase 0 (t == 0)
    plt.scatter(X[t == 0, 0], X[t == 0, 1],
                color='blue', label='Clase 0', alpha=0.6)

    # Clase 1 (t == 1)
    plt.scatter(X[t == 1, 0], X[t == 1, 1],
                color='red', label='Clase 1', alpha=0.6)

    # Construcción de la recta
    # Generar valores de x1 dentro del rango de los datos
    x_vals = np.linspace(np.min(X[:,0]), np.max(X[:,0]), 100)

    # Caso general (w2 != 0)
    if abs(w[1]) > 1e-10:
        y_vals = (-w[0]*x_vals - w[2]) / w[1]
        plt.plot(x_vals, y_vals, 'k-', label='Frontera de decisión')

    # Caso especial: recta vertical
    else:
        x_const = -w[2] / w[0]
        plt.axvline(x=x_const, color='k', label='Recta vertical')

    plt.xlabel("$x_1$")
    plt.ylabel("$x_2$")
    plt.title("Frontera de decisión sobre los datos")

    plt.legend()
    plt.grid()

    plt.show()

# Ejemplo de vector de parámetros
w = np.array([1, -1, 0])

# Graficar frontera de decisión
plot_recta(w, X, t)

"""### Análisis de la frontera de decisión

La recta obtenida presenta una inclinación positiva y atraviesa la región central de los datos, separando parcialmente las clases.

Se observa que la frontera de decisión logra capturar la tendencia general de separación entre las clases, sin embargo, existe un solapamiento significativo, lo que genera errores de clasificación.

Este comportamiento es consistente con el análisis previo del conjunto de datos, donde se evidenció que las clases no son perfectamente separables de manera lineal.

Es importante destacar que el vector de parámetros $w$ utilizado en este apartado no es óptimo, sino que se emplea únicamente para ilustrar la construcción de la frontera de decisión.

## Función de pérdida (Punto c)

Se define una función que permite evaluar qué tan bueno es un vector de parámetros $w$ para clasificar los datos.

La función de pérdida en regresión logística está dada por:

$$
f(w) = -\frac{1}{m} \sum_{i=1}^{m} \left[ t_i \log(y_i) + (1 - t_i)\log(1 - y_i) \right]
$$

donde:

$$
y_i = \frac{1}{1 + e^{-w^T z^{(i)}}}
$$

y $z^{(i)} = (x_1^{(i)}, x_2^{(i)}, 1)$.

Esta función mide el error del modelo al comparar las predicciones $y_i$ con las etiquetas reales $t_i$.
"""

import numpy as np

def sigmoid(z):
    """
    Función sigmoide:
    transforma cualquier valor real en un valor entre 0 y 1
    """
    return 1 / (1 + np.exp(-z))

def loss_function(w, X, t):
    """
    Calcula la función de pérdida de regresión logística

    w: vector de parámetros (w1, w2, w3)
    X: matriz de datos (x1, x2)
    t: etiquetas (0 o 1)
    """

    m = len(t)

    # Construir z = (x1, x2, 1)
    Z = np.hstack([X, np.ones((m,1))])

    # Predicciones
    y = sigmoid(Z @ w)

    # Evitar log(0)
    epsilon = 1e-10
    y = np.clip(y, epsilon, 1 - epsilon)

    # Función de pérdida
    f = -(1/m) * np.sum(t * np.log(y) + (1 - t) * np.log(1 - y))

    return f

"""### Interpretación

La función de pérdida mide la diferencia entre las predicciones del modelo y las etiquetas reales.

- Si $y_i$ es cercano a $t_i$, la pérdida es pequeña.
- Si $y_i$ es muy diferente de $t_i$, la pérdida aumenta.

Por lo tanto, valores pequeños de $f(w)$ indican que el modelo clasifica mejor los datos.


"""

# Ejemplo de vector w
w = np.array([1, -1, 0])

# Calcular pérdida
valor_loss = loss_function(w, X, t)

print("f(w) =", valor_loss)

"""### Relación con los siguientes apartados

La función de pérdida será utilizada para comparar distintos vectores de parámetros $w$.

En particular, en el punto (d) se evaluarán varios candidatos y se seleccionará aquel que produzca el menor valor de $f(w)$, ya que esto indica una mejor capacidad de clasificación.

## Evaluación de candidatos (Punto d)

En este apartado se evalúan distintos vectores de parámetros $w$ con el objetivo de comparar su desempeño como clasificadores.

Cada candidato define una frontera de decisión diferente, y su calidad se mide mediante la función de pérdida $f(w)$.

Se espera que el mejor clasificador sea aquel que minimice el valor de la función de pérdida.
"""

# Candidatos dados en el enunciado
candidatos = [
    np.array([0.0603, 4.0364, 1.3192]),
    np.array([-1.345, 3.597, -0.588]),
    np.array([0.0603, 1.000, 0.502])
]

# Evaluar cada candidato
for i, w in enumerate(candidatos):
    valor = loss_function(w, X, t)
    print(f"Candidato {i+1}:")
    print("w =", w)
    print("f(w) =", valor)
    print("-"*40)

"""### Análisis de resultados

Se calcula el valor de la función de pérdida para cada candidato.

Dado que la función de pérdida mide el error del modelo, el mejor vector de parámetros será aquel que produzca el menor valor de $f(w)$.

Esto indica que las predicciones del modelo son más cercanas a las etiquetas reales.
"""

# Encontrar el mejor candidato
valores = [loss_function(w, X, t) for w in candidatos]

mejor_idx = np.argmin(valores)
mejor_w = candidatos[mejor_idx]

print("Mejor candidato:", mejor_idx + 1)
print("w óptimo:", mejor_w)

"""## Análisis visual de los candidatos (Punto e)

En este apartado se grafican las fronteras de decisión asociadas a cada uno de los vectores $w$ propuestos en el punto (d).

El objetivo es comparar visualmente la capacidad de cada modelo para separar las clases y relacionar esta observación con los valores obtenidos de la función de pérdida $f(w)$.
"""

for i, w in enumerate(candidatos):
    print(f"Candidato {i+1}")
    plot_recta(w, X, t)

"""### Análisis de resultados

A partir de los valores obtenidos de la función de pérdida, se observa que el candidato 3 presenta el menor valor de $f(w)$, lo que indica un mejor desempeño del modelo.

Aunque visualmente su frontera de decisión no separa perfectamente las clases, logra un mejor ajuste global en términos probabilísticos, lo cual es consistente con la naturaleza de la regresión logística.

Esto evidencia que la mejor frontera de decisión no necesariamente corresponde a la que visualmente parece más separadora, sino a aquella que minimiza la función de pérdida.

## Gradiente y Hessiana (Punto f)

En este apartado se implementan el gradiente y la matriz Hessiana de la función de pérdida de la regresión logística.

El gradiente está dado por:

$$
\nabla f(w) = \frac{1}{m} \sum_{i=1}^{m} (y_i - t_i)\, z^{(i)}
$$

y la matriz Hessiana por:

$$
F(w) = \frac{1}{m} \sum_{i=1}^{m} y_i (1 - y_i)\, z^{(i)} (z^{(i)})^T
$$

Estas expresiones permiten analizar la pendiente y la curvatura de la función de pérdida.
"""

def gradient(w, X, t):
    """
    Calcula el gradiente de la función de pérdida

    w: vector de parámetros
    X: datos
    t: etiquetas
    """

    m = len(t)

    # Construir z = (x1, x2, 1)
    Z = np.hstack([X, np.ones((m,1))])

    # Predicciones
    y = sigmoid(Z @ w)

    # Gradiente
    grad = (1/m) * (Z.T @ (y - t))

    return grad

def hessian(w, X, t):
    """
    Calcula la matriz Hessiana
    """

    m = len(t)

    Z = np.hstack([X, np.ones((m,1))])

    y = sigmoid(Z @ w)

    # Matriz diagonal
    D = np.diag(y * (1 - y))

    # Hessiana
    H = (1/m) * (Z.T @ D @ Z)

    return H

for i, w in enumerate(candidatos):
    print(f"Candidato {i+1}")

    grad = gradient(w, X, t)
    H = hessian(w, X, t)

    print("Gradiente:", grad)
    print("Norma del gradiente:", np.linalg.norm(grad))
    print("Hessiana:\n", H)
    print("-"*50)

"""### Análisis del gradiente

El gradiente indica la dirección de mayor incremento de la función de pérdida.

- Si el gradiente es cercano a cero, el modelo se encuentra cerca de un punto óptimo.
- Si el gradiente es grande, el modelo aún puede mejorar significativamente.

Por lo tanto, se esperaba que el mejor candidato (con menor $f(w)$) tuviera un gradiente de menor magnitud.

### Análisis de la Hessiana

La Hessiana describe la curvatura de la función de pérdida.

En regresión logística, la Hessiana es siempre positiva definida, lo que implica que la función de pérdida es convexa.

Esto garantiza la existencia de un único mínimo global, facilitando el proceso de optimización.

### Conclusión

El análisis del gradiente y la Hessiana permite comprender el comportamiento de la función de pérdida.

Se observa que el mejor candidato no solo minimiza la función de pérdida, sino que también presenta un gradiente de menor magnitud, lo cual indica cercanía a un punto óptimo.

Además, la positividad de la Hessiana confirma que la función es convexa, lo que garantiza estabilidad en la optimización del modelo.
"""

!jupyter nbconvert --to html "challenge_week3.ipynb" #Crear .html